name: Build my own

on:
    workflow_dispatch:

jobs:
    build-test-push-x86:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Login to Nexus
            uses: docker/login-action@v3
            with:
              registry: dev-docker.hops.works
              username: ${{ secrets.NEXUS_USER }}
              password: ${{ secrets.NEXUS_PASSWORD }}   
    
          - name: Build X86 image
            run: |
              X86_IMAGE_ID=dev-docker.hops.works/mahmoud/hopsworks/rondb:22.10.6-0.8
              docker buildx build . \
                  --tag $X86_IMAGE_ID \
                  --build-arg RONDB_VERSION=22.10.6 \
                  --build-arg RONDB_TARBALL_LOCAL_REMOTE=remote \
                  --build-arg RONDB_X86_TARBALL_URI=https://repo.hops.works/master/rondb-22.10.6-linux-glibc2.28-x86_64.tar.gz
  